
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BATBAT101P01': typeof import("../components/BAT/BAT101P01.vue")['default']
    'BATBAT102P01': typeof import("../components/BAT/BAT102P01.vue")['default']
    'COMCOM001C01': typeof import("../components/COM/COM001C01.vue")['default']
    'COMCOM001C02': typeof import("../components/COM/COM001C02.vue")['default']
    'COMPOPCOM001C01': typeof import("../components/COM/POP/COM001C01.vue")['default']
    'COMPOPCOM001C02': typeof import("../components/COM/POP/COM001C02.vue")['default']
    'COMPOPCOM001P01': typeof import("../components/COM/POP/COM001P01.vue")['default']
    'COMPOPCOM001P02': typeof import("../components/COM/POP/COM001P02.vue")['default']
    'COMPOPCOM001P03': typeof import("../components/COM/POP/COM001P03.vue")['default']
    'COMPOPCOM002P01': typeof import("../components/COM/POP/COM002P01.vue")['default']
    'COMPOPCOM002P02': typeof import("../components/COM/POP/COM002P02.vue")['default']
    'COMPOPCOM002P03': typeof import("../components/COM/POP/COM002P03.vue")['default']
    'COMPOPCOM002P04': typeof import("../components/COM/POP/COM002P04.vue")['default']
    'CONBackPOPUPCON001P01': typeof import("../components/CON_back/POPUP/CON001P01.vue")['default']
    'CONBackPOPUPCON002P01': typeof import("../components/CON_back/POPUP/CON002P01.vue")['default']
    'EXCEXC100P00': typeof import("../components/EXC/EXC100P00.vue")['default']
    'EXCEXC100P01': typeof import("../components/EXC/EXC100P01.vue")['default']
    'LOGLOG001M01C00': typeof import("../components/LOG/LOG001M01C00.vue")['default']
    'LOGLOG001M01C01': typeof import("../components/LOG/LOG001M01C01.vue")['default']
    'LOGLOG001M01C02': typeof import("../components/LOG/LOG001M01C02.vue")['default']
    'LOGLOG001P01': typeof import("../components/LOG/LOG001P01.vue")['default']
    'MEMMEM001P01': typeof import("../components/MEM/MEM001P01.vue")['default']
    'MEMMEM002P02': typeof import("../components/MEM/MEM002P02.vue")['default']
    'MEMMEM003P01': typeof import("../components/MEM/MEM003P01.vue")['default']
    'MEMMEM010P01': typeof import("../components/MEM/MEM010P01.vue")['default']
    'MEMMEM010P03': typeof import("../components/MEM/MEM010P03.vue")['default']
    'MEMMEM011P01': typeof import("../components/MEM/MEM011P01.vue")['default']
    'NOTNOT001P01': typeof import("../components/NOT/NOT001P01.vue")['default']
    'NOTNOT020C02': typeof import("../components/NOT/NOT020C02.vue")['default']
    'CommonComAgGrid': typeof import("../components/common/ComAgGrid.vue")['default']
    'CommonComAgGridBasic': typeof import("../components/common/ComAgGridBasic.vue")['default']
    'CommonComCheckbox': typeof import("../components/common/ComCheckbox.vue")['default']
    'CommonComDatePicker': typeof import("../components/common/ComDatePicker.vue")['default']
    'CommonComImage': typeof import("../components/common/ComImage.vue")['default']
    'CommonComPagenation': typeof import("../components/common/ComPagenation.vue")['default']
    'CommonComRadioButton': typeof import("../components/common/ComRadioButton.vue")['default']
    'CommonComResize': typeof import("../components/common/ComResize.vue")['default']
    'CommonComSelectBox': typeof import("../components/common/ComSelectBox.vue")['default']
    'CommonComSpinner': typeof import("../components/common/ComSpinner.vue")['default']
    'CommonComSwiper': typeof import("../components/common/ComSwiper.vue")['default']
    'CommonLayerPopup': typeof import("../components/common/LayerPopup.vue")['default']
    'CommonDocViewer': typeof import("../components/common/doc/DocViewer.vue")['default']
    'CommonPdfMakeLayout': typeof import("../components/common/pdf/PdfMakeLayout.vue")['default']
    'CommonPdfLoadDynamicUrlPDF': typeof import("../components/common/pdf/loadDynamicUrlPDF.vue")['default']
    'CommonPdfPagination': typeof import("../components/common/pdf/pagination.vue")['default']
    'CommonPdfRender': typeof import("../components/common/pdf/pdfRender.vue")['default']
    'DocViewer': typeof import("../components/doc/DocViewer.vue")['default']
    'LoginForm': typeof import("../components/login/LoginForm.vue")['default']
    'Main': typeof import("../components/main/Main.vue")['default']
    'PdfMakeLayout': typeof import("../components/pdf/PdfMakeLayout.vue")['default']
    'PdfLoadDynamicUrlPDF': typeof import("../components/pdf/loadDynamicUrlPDF.vue")['default']
    'PdfPagination': typeof import("../components/pdf/pagination.vue")['default']
    'PdfRender': typeof import("../components/pdf/pdfRender.vue")['default']
    'ADMADM100M01': typeof import("../pages/ADM/ADM100M01.vue")['default']
    'ADMADM101M01': typeof import("../pages/ADM/ADM101M01.vue")['default']
    'ADMADM102M01': typeof import("../pages/ADM/ADM102M01.vue")['default']
    'ADMADM103M01': typeof import("../pages/ADM/ADM103M01.vue")['default']
    'ADMADM104M01': typeof import("../pages/ADM/ADM104M01.vue")['default']
    'ADMADM105M01': typeof import("../pages/ADM/ADM105M01.vue")['default']
    'ADMADM106M01': typeof import("../pages/ADM/ADM106M01.vue")['default']
    'ADMADM107M01': typeof import("../pages/ADM/ADM107M01.vue")['default']
    'ADMADM108M01': typeof import("../pages/ADM/ADM108M01.vue")['default']
    'ADMADM109M01': typeof import("../pages/ADM/ADM109M01.vue")['default']
    'ADMADM110M01': typeof import("../pages/ADM/ADM110M01.vue")['default']
    'ADMADM111M01': typeof import("../pages/ADM/ADM111M01.vue")['default']
    'ADMADM112M01': typeof import("../pages/ADM/ADM112M01.vue")['default']
    'ADMADM113M01': typeof import("../pages/ADM/ADM113M01.vue")['default']
    'BATBAT101M01': typeof import("../pages/BAT/BAT101M01.vue")['default']
    'BATBAT102M01': typeof import("../pages/BAT/BAT102M01.vue")['default']
    'BATBAT103M01': typeof import("../pages/BAT/BAT103M01.vue")['default']
    'COMCOM002M00': typeof import("../pages/COM/COM002M00.vue")['default']
    'CONBackCON001M00': typeof import("../pages/CON_back/CON001M00.vue")['default']
    'CONBackCON001M01': typeof import("../pages/CON_back/CON001M01.vue")['default']
    'CONBackCON001S01': typeof import("../pages/CON_back/CON001S01.vue")['default']
    'CONBackCON001S02': typeof import("../pages/CON_back/CON001S02.vue")['default']
    'CONBackCON001S03': typeof import("../pages/CON_back/CON001S03.vue")['default']
    'CONBackCON002M00': typeof import("../pages/CON_back/CON002M00.vue")['default']
    'CONBackCON002S01': typeof import("../pages/CON_back/CON002S01.vue")['default']
    'CONBackCON002S02': typeof import("../pages/CON_back/CON002S02.vue")['default']
    'CONBackCON002S03': typeof import("../pages/CON_back/CON002S03.vue")['default']
    'COVCOV001M01': typeof import("../pages/COV/COV001M01.vue")['default']
    'COVCOV100M00': typeof import("../pages/COV/COV100M00.vue")['default']
    'COVCOV100S01': typeof import("../pages/COV/COV100S01.vue")['default']
    'COVCOV100S02': typeof import("../pages/COV/COV100S02.vue")['default']
    'COVCOV200M00': typeof import("../pages/COV/COV200M00.vue")['default']
    'EXCEXC100M00': typeof import("../pages/EXC/EXC100M00.vue")['default']
    'HCOHCO101M01': typeof import("../pages/HCO/HCO101M01.vue")['default']
    'HOMHOM001M00': typeof import("../pages/HOM/HOM001M00.vue")['default']
    'LOGLOG001M00': typeof import("../pages/LOG/LOG001M00.vue")['default']
    'LOGLOG002M00': typeof import("../pages/LOG/LOG002M00.vue")['default']
    'MAIN': typeof import("../pages/MAIN/index.vue")['default']
    'MEMMEM010S01': typeof import("../pages/MEM/MEM010S01.vue")['default']
    'MEMMEM010S02': typeof import("../pages/MEM/MEM010S02.vue")['default']
    'MEMMEM011S02': typeof import("../pages/MEM/MEM011S02.vue")['default']
    'MEMMEM011S03': typeof import("../pages/MEM/MEM011S03.vue")['default']
    'MEMMEM101M01': typeof import("../pages/MEM/MEM101M01.vue")['default']
    'MEMMEM201M01': typeof import("../pages/MEM/MEM201M01.vue")['default']
    'MEMMEM201M02': typeof import("../pages/MEM/MEM201M02.vue")['default']
    'MEMMEM201M03': typeof import("../pages/MEM/MEM201M03.vue")['default']
    'MENMEN001M01': typeof import("../pages/MEN/MEN001M01.vue")['default']
    'MENMEN004M01': typeof import("../pages/MEN/MEN004M01.vue")['default']
    'MENMEN004S01': typeof import("../pages/MEN/MEN004S01.vue")['default']
    'MENMEN005M01': typeof import("../pages/MEN/MEN005M01.vue")['default']
    'MENMEN005S01': typeof import("../pages/MEN/MEN005S01.vue")['default']
    'MENMEN006M01': typeof import("../pages/MEN/MEN006M01.vue")['default']
    'MENMEN007M01': typeof import("../pages/MEN/MEN007M01.vue")['default']
    'NOTNOT010M00': typeof import("../pages/NOT/NOT010M00.vue")['default']
    'NOTNOT010S01': typeof import("../pages/NOT/NOT010S01.vue")['default']
    'NOTNOT010S02': typeof import("../pages/NOT/NOT010S02.vue")['default']
    'NOTNOT020M00': typeof import("../pages/NOT/NOT020M00.vue")['default']
    'Idx': typeof import("../pages/idx.vue")['default']
    'PubAdminADMADM0108M01': typeof import("../pages/pub/admin/ADM/ADM0108M01.vue")['default']
    'PubAdminADMADM100M01': typeof import("../pages/pub/admin/ADM/ADM100M01.vue")['default']
    'PubAdminADMADM101M01': typeof import("../pages/pub/admin/ADM/ADM101M01.vue")['default']
    'PubAdminADMADM107M01': typeof import("../pages/pub/admin/ADM/ADM107M01.vue")['default']
    'PubAdminADMADM112M01': typeof import("../pages/pub/admin/ADM/ADM112M01.vue")['default']
    'PubAdminADMADMS0017': typeof import("../pages/pub/admin/ADM/ADMS0017.vue")['default']
    'PubAdminADMADMS0018': typeof import("../pages/pub/admin/ADM/ADMS0018.vue")['default']
    'PubAdminADMADMS0019': typeof import("../pages/pub/admin/ADM/ADMS0019.vue")['default']
    'PubAdminADMADMS0020': typeof import("../pages/pub/admin/ADM/ADMS0020.vue")['default']
    'PubAdminADMADMS0021': typeof import("../pages/pub/admin/ADM/ADMS0021.vue")['default']
    'PubAdminADMADMS0023': typeof import("../pages/pub/admin/ADM/ADMS0023.vue")['default']
    'PubAdminADMADMS0024': typeof import("../pages/pub/admin/ADM/ADMS0024.vue")['default']
    'PubAdminADMADMS0025': typeof import("../pages/pub/admin/ADM/ADMS0025.vue")['default']
    'PubAdminADMADMS0026': typeof import("../pages/pub/admin/ADM/ADMS0026.vue")['default']
    'PubAdminADMADMS0045': typeof import("../pages/pub/admin/ADM/ADMS0045.vue")['default']
    'PubAdminADMADMS0P06': typeof import("../pages/pub/admin/ADM/ADMS0P06.vue")['default']
    'PubAdminBATBAT101M01': typeof import("../pages/pub/admin/BAT/BAT101M01.vue")['default']
    'PubAdminBATBAT101P01': typeof import("../pages/pub/admin/BAT/BAT101P01.vue")['default']
    'PubAdminBATBAT102P01': typeof import("../pages/pub/admin/BAT/BAT102P01.vue")['default']
    'PubAdminHOM001M01': typeof import("../pages/pub/admin/HOM001M01.vue")['default']
    'PubAdminLOG001M00': typeof import("../pages/pub/admin/LOG001M00.vue")['default']
    'PubAdminLOG001P09': typeof import("../pages/pub/admin/LOG001P09.vue")['default']
    'PubAdminLOG002M00': typeof import("../pages/pub/admin/LOG002M00.vue")['default']
    'PubAdminMEMMEM001M00': typeof import("../pages/pub/admin/MEM/MEM001M00.vue")['default']
    'PubAdminMEMMEM201M03': typeof import("../pages/pub/admin/MEM/MEM201M03.vue")['default']
    'PubAdminTemplate': typeof import("../pages/pub/admin/Template.vue")['default']
    'PubPublistAdmin': typeof import("../pages/pub/publist_admin.vue")['default']
    'SampleAdminList': typeof import("../pages/sample/Admin_list.vue")['default']
    'SampleBasicGridViewer': typeof import("../pages/sample/BasicGridViewer.vue")['default']
    'SampleComponentLayout': typeof import("../pages/sample/ComponentLayout.vue")['default']
    'SampleDocViewer': typeof import("../pages/sample/DocViewer.vue")['default']
    'SampleEmptyLayout': typeof import("../pages/sample/EmptyLayout.vue")['default']
    'SampleGridViewer': typeof import("../pages/sample/GridViewer.vue")['default']
    'SampleLoginNoEnterPage': typeof import("../pages/sample/LoginNoEnterPage.vue")['default']
    'SamplePdfMakeViewer': typeof import("../pages/sample/PdfMakeViewer.vue")['default']
    'SamplePdfMakeViewerType2': typeof import("../pages/sample/PdfMakeViewerType2.vue")['default']
    'SamplePdfViewer': typeof import("../pages/sample/PdfViewer.vue")['default']
    'Sample': typeof import("../pages/sample/Sample.vue")['default']
    'SampleTemplate': typeof import("../pages/sample/Template.vue")['default']
    'SampleValidation': typeof import("../pages/sample/Validation.vue")['default']
    'SampleMenuList': typeof import("../pages/sample/menu_list.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBATBAT101P01': typeof import("../components/BAT/BAT101P01.vue")['default']
    'LazyBATBAT102P01': typeof import("../components/BAT/BAT102P01.vue")['default']
    'LazyCOMCOM001C01': typeof import("../components/COM/COM001C01.vue")['default']
    'LazyCOMCOM001C02': typeof import("../components/COM/COM001C02.vue")['default']
    'LazyCOMPOPCOM001C01': typeof import("../components/COM/POP/COM001C01.vue")['default']
    'LazyCOMPOPCOM001C02': typeof import("../components/COM/POP/COM001C02.vue")['default']
    'LazyCOMPOPCOM001P01': typeof import("../components/COM/POP/COM001P01.vue")['default']
    'LazyCOMPOPCOM001P02': typeof import("../components/COM/POP/COM001P02.vue")['default']
    'LazyCOMPOPCOM001P03': typeof import("../components/COM/POP/COM001P03.vue")['default']
    'LazyCOMPOPCOM002P01': typeof import("../components/COM/POP/COM002P01.vue")['default']
    'LazyCOMPOPCOM002P02': typeof import("../components/COM/POP/COM002P02.vue")['default']
    'LazyCOMPOPCOM002P03': typeof import("../components/COM/POP/COM002P03.vue")['default']
    'LazyCOMPOPCOM002P04': typeof import("../components/COM/POP/COM002P04.vue")['default']
    'LazyCONBackPOPUPCON001P01': typeof import("../components/CON_back/POPUP/CON001P01.vue")['default']
    'LazyCONBackPOPUPCON002P01': typeof import("../components/CON_back/POPUP/CON002P01.vue")['default']
    'LazyEXCEXC100P00': typeof import("../components/EXC/EXC100P00.vue")['default']
    'LazyEXCEXC100P01': typeof import("../components/EXC/EXC100P01.vue")['default']
    'LazyLOGLOG001M01C00': typeof import("../components/LOG/LOG001M01C00.vue")['default']
    'LazyLOGLOG001M01C01': typeof import("../components/LOG/LOG001M01C01.vue")['default']
    'LazyLOGLOG001M01C02': typeof import("../components/LOG/LOG001M01C02.vue")['default']
    'LazyLOGLOG001P01': typeof import("../components/LOG/LOG001P01.vue")['default']
    'LazyMEMMEM001P01': typeof import("../components/MEM/MEM001P01.vue")['default']
    'LazyMEMMEM002P02': typeof import("../components/MEM/MEM002P02.vue")['default']
    'LazyMEMMEM003P01': typeof import("../components/MEM/MEM003P01.vue")['default']
    'LazyMEMMEM010P01': typeof import("../components/MEM/MEM010P01.vue")['default']
    'LazyMEMMEM010P03': typeof import("../components/MEM/MEM010P03.vue")['default']
    'LazyMEMMEM011P01': typeof import("../components/MEM/MEM011P01.vue")['default']
    'LazyNOTNOT001P01': typeof import("../components/NOT/NOT001P01.vue")['default']
    'LazyNOTNOT020C02': typeof import("../components/NOT/NOT020C02.vue")['default']
    'LazyCommonComAgGrid': typeof import("../components/common/ComAgGrid.vue")['default']
    'LazyCommonComAgGridBasic': typeof import("../components/common/ComAgGridBasic.vue")['default']
    'LazyCommonComCheckbox': typeof import("../components/common/ComCheckbox.vue")['default']
    'LazyCommonComDatePicker': typeof import("../components/common/ComDatePicker.vue")['default']
    'LazyCommonComImage': typeof import("../components/common/ComImage.vue")['default']
    'LazyCommonComPagenation': typeof import("../components/common/ComPagenation.vue")['default']
    'LazyCommonComRadioButton': typeof import("../components/common/ComRadioButton.vue")['default']
    'LazyCommonComResize': typeof import("../components/common/ComResize.vue")['default']
    'LazyCommonComSelectBox': typeof import("../components/common/ComSelectBox.vue")['default']
    'LazyCommonComSpinner': typeof import("../components/common/ComSpinner.vue")['default']
    'LazyCommonComSwiper': typeof import("../components/common/ComSwiper.vue")['default']
    'LazyCommonLayerPopup': typeof import("../components/common/LayerPopup.vue")['default']
    'LazyCommonDocViewer': typeof import("../components/common/doc/DocViewer.vue")['default']
    'LazyCommonPdfMakeLayout': typeof import("../components/common/pdf/PdfMakeLayout.vue")['default']
    'LazyCommonPdfLoadDynamicUrlPDF': typeof import("../components/common/pdf/loadDynamicUrlPDF.vue")['default']
    'LazyCommonPdfPagination': typeof import("../components/common/pdf/pagination.vue")['default']
    'LazyCommonPdfRender': typeof import("../components/common/pdf/pdfRender.vue")['default']
    'LazyDocViewer': typeof import("../components/doc/DocViewer.vue")['default']
    'LazyLoginForm': typeof import("../components/login/LoginForm.vue")['default']
    'LazyMain': typeof import("../components/main/Main.vue")['default']
    'LazyPdfMakeLayout': typeof import("../components/pdf/PdfMakeLayout.vue")['default']
    'LazyPdfLoadDynamicUrlPDF': typeof import("../components/pdf/loadDynamicUrlPDF.vue")['default']
    'LazyPdfPagination': typeof import("../components/pdf/pagination.vue")['default']
    'LazyPdfRender': typeof import("../components/pdf/pdfRender.vue")['default']
    'LazyADMADM100M01': typeof import("../pages/ADM/ADM100M01.vue")['default']
    'LazyADMADM101M01': typeof import("../pages/ADM/ADM101M01.vue")['default']
    'LazyADMADM102M01': typeof import("../pages/ADM/ADM102M01.vue")['default']
    'LazyADMADM103M01': typeof import("../pages/ADM/ADM103M01.vue")['default']
    'LazyADMADM104M01': typeof import("../pages/ADM/ADM104M01.vue")['default']
    'LazyADMADM105M01': typeof import("../pages/ADM/ADM105M01.vue")['default']
    'LazyADMADM106M01': typeof import("../pages/ADM/ADM106M01.vue")['default']
    'LazyADMADM107M01': typeof import("../pages/ADM/ADM107M01.vue")['default']
    'LazyADMADM108M01': typeof import("../pages/ADM/ADM108M01.vue")['default']
    'LazyADMADM109M01': typeof import("../pages/ADM/ADM109M01.vue")['default']
    'LazyADMADM110M01': typeof import("../pages/ADM/ADM110M01.vue")['default']
    'LazyADMADM111M01': typeof import("../pages/ADM/ADM111M01.vue")['default']
    'LazyADMADM112M01': typeof import("../pages/ADM/ADM112M01.vue")['default']
    'LazyADMADM113M01': typeof import("../pages/ADM/ADM113M01.vue")['default']
    'LazyBATBAT101M01': typeof import("../pages/BAT/BAT101M01.vue")['default']
    'LazyBATBAT102M01': typeof import("../pages/BAT/BAT102M01.vue")['default']
    'LazyBATBAT103M01': typeof import("../pages/BAT/BAT103M01.vue")['default']
    'LazyCOMCOM002M00': typeof import("../pages/COM/COM002M00.vue")['default']
    'LazyCONBackCON001M00': typeof import("../pages/CON_back/CON001M00.vue")['default']
    'LazyCONBackCON001M01': typeof import("../pages/CON_back/CON001M01.vue")['default']
    'LazyCONBackCON001S01': typeof import("../pages/CON_back/CON001S01.vue")['default']
    'LazyCONBackCON001S02': typeof import("../pages/CON_back/CON001S02.vue")['default']
    'LazyCONBackCON001S03': typeof import("../pages/CON_back/CON001S03.vue")['default']
    'LazyCONBackCON002M00': typeof import("../pages/CON_back/CON002M00.vue")['default']
    'LazyCONBackCON002S01': typeof import("../pages/CON_back/CON002S01.vue")['default']
    'LazyCONBackCON002S02': typeof import("../pages/CON_back/CON002S02.vue")['default']
    'LazyCONBackCON002S03': typeof import("../pages/CON_back/CON002S03.vue")['default']
    'LazyCOVCOV001M01': typeof import("../pages/COV/COV001M01.vue")['default']
    'LazyCOVCOV100M00': typeof import("../pages/COV/COV100M00.vue")['default']
    'LazyCOVCOV100S01': typeof import("../pages/COV/COV100S01.vue")['default']
    'LazyCOVCOV100S02': typeof import("../pages/COV/COV100S02.vue")['default']
    'LazyCOVCOV200M00': typeof import("../pages/COV/COV200M00.vue")['default']
    'LazyEXCEXC100M00': typeof import("../pages/EXC/EXC100M00.vue")['default']
    'LazyHCOHCO101M01': typeof import("../pages/HCO/HCO101M01.vue")['default']
    'LazyHOMHOM001M00': typeof import("../pages/HOM/HOM001M00.vue")['default']
    'LazyLOGLOG001M00': typeof import("../pages/LOG/LOG001M00.vue")['default']
    'LazyLOGLOG002M00': typeof import("../pages/LOG/LOG002M00.vue")['default']
    'LazyMAIN': typeof import("../pages/MAIN/index.vue")['default']
    'LazyMEMMEM010S01': typeof import("../pages/MEM/MEM010S01.vue")['default']
    'LazyMEMMEM010S02': typeof import("../pages/MEM/MEM010S02.vue")['default']
    'LazyMEMMEM011S02': typeof import("../pages/MEM/MEM011S02.vue")['default']
    'LazyMEMMEM011S03': typeof import("../pages/MEM/MEM011S03.vue")['default']
    'LazyMEMMEM101M01': typeof import("../pages/MEM/MEM101M01.vue")['default']
    'LazyMEMMEM201M01': typeof import("../pages/MEM/MEM201M01.vue")['default']
    'LazyMEMMEM201M02': typeof import("../pages/MEM/MEM201M02.vue")['default']
    'LazyMEMMEM201M03': typeof import("../pages/MEM/MEM201M03.vue")['default']
    'LazyMENMEN001M01': typeof import("../pages/MEN/MEN001M01.vue")['default']
    'LazyMENMEN004M01': typeof import("../pages/MEN/MEN004M01.vue")['default']
    'LazyMENMEN004S01': typeof import("../pages/MEN/MEN004S01.vue")['default']
    'LazyMENMEN005M01': typeof import("../pages/MEN/MEN005M01.vue")['default']
    'LazyMENMEN005S01': typeof import("../pages/MEN/MEN005S01.vue")['default']
    'LazyMENMEN006M01': typeof import("../pages/MEN/MEN006M01.vue")['default']
    'LazyMENMEN007M01': typeof import("../pages/MEN/MEN007M01.vue")['default']
    'LazyNOTNOT010M00': typeof import("../pages/NOT/NOT010M00.vue")['default']
    'LazyNOTNOT010S01': typeof import("../pages/NOT/NOT010S01.vue")['default']
    'LazyNOTNOT010S02': typeof import("../pages/NOT/NOT010S02.vue")['default']
    'LazyNOTNOT020M00': typeof import("../pages/NOT/NOT020M00.vue")['default']
    'LazyIdx': typeof import("../pages/idx.vue")['default']
    'LazyPubAdminADMADM0108M01': typeof import("../pages/pub/admin/ADM/ADM0108M01.vue")['default']
    'LazyPubAdminADMADM100M01': typeof import("../pages/pub/admin/ADM/ADM100M01.vue")['default']
    'LazyPubAdminADMADM101M01': typeof import("../pages/pub/admin/ADM/ADM101M01.vue")['default']
    'LazyPubAdminADMADM107M01': typeof import("../pages/pub/admin/ADM/ADM107M01.vue")['default']
    'LazyPubAdminADMADM112M01': typeof import("../pages/pub/admin/ADM/ADM112M01.vue")['default']
    'LazyPubAdminADMADMS0017': typeof import("../pages/pub/admin/ADM/ADMS0017.vue")['default']
    'LazyPubAdminADMADMS0018': typeof import("../pages/pub/admin/ADM/ADMS0018.vue")['default']
    'LazyPubAdminADMADMS0019': typeof import("../pages/pub/admin/ADM/ADMS0019.vue")['default']
    'LazyPubAdminADMADMS0020': typeof import("../pages/pub/admin/ADM/ADMS0020.vue")['default']
    'LazyPubAdminADMADMS0021': typeof import("../pages/pub/admin/ADM/ADMS0021.vue")['default']
    'LazyPubAdminADMADMS0023': typeof import("../pages/pub/admin/ADM/ADMS0023.vue")['default']
    'LazyPubAdminADMADMS0024': typeof import("../pages/pub/admin/ADM/ADMS0024.vue")['default']
    'LazyPubAdminADMADMS0025': typeof import("../pages/pub/admin/ADM/ADMS0025.vue")['default']
    'LazyPubAdminADMADMS0026': typeof import("../pages/pub/admin/ADM/ADMS0026.vue")['default']
    'LazyPubAdminADMADMS0045': typeof import("../pages/pub/admin/ADM/ADMS0045.vue")['default']
    'LazyPubAdminADMADMS0P06': typeof import("../pages/pub/admin/ADM/ADMS0P06.vue")['default']
    'LazyPubAdminBATBAT101M01': typeof import("../pages/pub/admin/BAT/BAT101M01.vue")['default']
    'LazyPubAdminBATBAT101P01': typeof import("../pages/pub/admin/BAT/BAT101P01.vue")['default']
    'LazyPubAdminBATBAT102P01': typeof import("../pages/pub/admin/BAT/BAT102P01.vue")['default']
    'LazyPubAdminHOM001M01': typeof import("../pages/pub/admin/HOM001M01.vue")['default']
    'LazyPubAdminLOG001M00': typeof import("../pages/pub/admin/LOG001M00.vue")['default']
    'LazyPubAdminLOG001P09': typeof import("../pages/pub/admin/LOG001P09.vue")['default']
    'LazyPubAdminLOG002M00': typeof import("../pages/pub/admin/LOG002M00.vue")['default']
    'LazyPubAdminMEMMEM001M00': typeof import("../pages/pub/admin/MEM/MEM001M00.vue")['default']
    'LazyPubAdminMEMMEM201M03': typeof import("../pages/pub/admin/MEM/MEM201M03.vue")['default']
    'LazyPubAdminTemplate': typeof import("../pages/pub/admin/Template.vue")['default']
    'LazyPubPublistAdmin': typeof import("../pages/pub/publist_admin.vue")['default']
    'LazySampleAdminList': typeof import("../pages/sample/Admin_list.vue")['default']
    'LazySampleBasicGridViewer': typeof import("../pages/sample/BasicGridViewer.vue")['default']
    'LazySampleComponentLayout': typeof import("../pages/sample/ComponentLayout.vue")['default']
    'LazySampleDocViewer': typeof import("../pages/sample/DocViewer.vue")['default']
    'LazySampleEmptyLayout': typeof import("../pages/sample/EmptyLayout.vue")['default']
    'LazySampleGridViewer': typeof import("../pages/sample/GridViewer.vue")['default']
    'LazySampleLoginNoEnterPage': typeof import("../pages/sample/LoginNoEnterPage.vue")['default']
    'LazySamplePdfMakeViewer': typeof import("../pages/sample/PdfMakeViewer.vue")['default']
    'LazySamplePdfMakeViewerType2': typeof import("../pages/sample/PdfMakeViewerType2.vue")['default']
    'LazySamplePdfViewer': typeof import("../pages/sample/PdfViewer.vue")['default']
    'LazySample': typeof import("../pages/sample/Sample.vue")['default']
    'LazySampleTemplate': typeof import("../pages/sample/Template.vue")['default']
    'LazySampleValidation': typeof import("../pages/sample/Validation.vue")['default']
    'LazySampleMenuList': typeof import("../pages/sample/menu_list.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BATBAT101P01: typeof import("../components/BAT/BAT101P01.vue")['default']
export const BATBAT102P01: typeof import("../components/BAT/BAT102P01.vue")['default']
export const COMCOM001C01: typeof import("../components/COM/COM001C01.vue")['default']
export const COMCOM001C02: typeof import("../components/COM/COM001C02.vue")['default']
export const COMPOPCOM001C01: typeof import("../components/COM/POP/COM001C01.vue")['default']
export const COMPOPCOM001C02: typeof import("../components/COM/POP/COM001C02.vue")['default']
export const COMPOPCOM001P01: typeof import("../components/COM/POP/COM001P01.vue")['default']
export const COMPOPCOM001P02: typeof import("../components/COM/POP/COM001P02.vue")['default']
export const COMPOPCOM001P03: typeof import("../components/COM/POP/COM001P03.vue")['default']
export const COMPOPCOM002P01: typeof import("../components/COM/POP/COM002P01.vue")['default']
export const COMPOPCOM002P02: typeof import("../components/COM/POP/COM002P02.vue")['default']
export const COMPOPCOM002P03: typeof import("../components/COM/POP/COM002P03.vue")['default']
export const COMPOPCOM002P04: typeof import("../components/COM/POP/COM002P04.vue")['default']
export const CONBackPOPUPCON001P01: typeof import("../components/CON_back/POPUP/CON001P01.vue")['default']
export const CONBackPOPUPCON002P01: typeof import("../components/CON_back/POPUP/CON002P01.vue")['default']
export const EXCEXC100P00: typeof import("../components/EXC/EXC100P00.vue")['default']
export const EXCEXC100P01: typeof import("../components/EXC/EXC100P01.vue")['default']
export const LOGLOG001M01C00: typeof import("../components/LOG/LOG001M01C00.vue")['default']
export const LOGLOG001M01C01: typeof import("../components/LOG/LOG001M01C01.vue")['default']
export const LOGLOG001M01C02: typeof import("../components/LOG/LOG001M01C02.vue")['default']
export const LOGLOG001P01: typeof import("../components/LOG/LOG001P01.vue")['default']
export const MEMMEM001P01: typeof import("../components/MEM/MEM001P01.vue")['default']
export const MEMMEM002P02: typeof import("../components/MEM/MEM002P02.vue")['default']
export const MEMMEM003P01: typeof import("../components/MEM/MEM003P01.vue")['default']
export const MEMMEM010P01: typeof import("../components/MEM/MEM010P01.vue")['default']
export const MEMMEM010P03: typeof import("../components/MEM/MEM010P03.vue")['default']
export const MEMMEM011P01: typeof import("../components/MEM/MEM011P01.vue")['default']
export const NOTNOT001P01: typeof import("../components/NOT/NOT001P01.vue")['default']
export const NOTNOT020C02: typeof import("../components/NOT/NOT020C02.vue")['default']
export const CommonComAgGrid: typeof import("../components/common/ComAgGrid.vue")['default']
export const CommonComAgGridBasic: typeof import("../components/common/ComAgGridBasic.vue")['default']
export const CommonComCheckbox: typeof import("../components/common/ComCheckbox.vue")['default']
export const CommonComDatePicker: typeof import("../components/common/ComDatePicker.vue")['default']
export const CommonComImage: typeof import("../components/common/ComImage.vue")['default']
export const CommonComPagenation: typeof import("../components/common/ComPagenation.vue")['default']
export const CommonComRadioButton: typeof import("../components/common/ComRadioButton.vue")['default']
export const CommonComResize: typeof import("../components/common/ComResize.vue")['default']
export const CommonComSelectBox: typeof import("../components/common/ComSelectBox.vue")['default']
export const CommonComSpinner: typeof import("../components/common/ComSpinner.vue")['default']
export const CommonComSwiper: typeof import("../components/common/ComSwiper.vue")['default']
export const CommonLayerPopup: typeof import("../components/common/LayerPopup.vue")['default']
export const CommonDocViewer: typeof import("../components/common/doc/DocViewer.vue")['default']
export const CommonPdfMakeLayout: typeof import("../components/common/pdf/PdfMakeLayout.vue")['default']
export const CommonPdfLoadDynamicUrlPDF: typeof import("../components/common/pdf/loadDynamicUrlPDF.vue")['default']
export const CommonPdfPagination: typeof import("../components/common/pdf/pagination.vue")['default']
export const CommonPdfRender: typeof import("../components/common/pdf/pdfRender.vue")['default']
export const DocViewer: typeof import("../components/doc/DocViewer.vue")['default']
export const LoginForm: typeof import("../components/login/LoginForm.vue")['default']
export const Main: typeof import("../components/main/Main.vue")['default']
export const PdfMakeLayout: typeof import("../components/pdf/PdfMakeLayout.vue")['default']
export const PdfLoadDynamicUrlPDF: typeof import("../components/pdf/loadDynamicUrlPDF.vue")['default']
export const PdfPagination: typeof import("../components/pdf/pagination.vue")['default']
export const PdfRender: typeof import("../components/pdf/pdfRender.vue")['default']
export const ADMADM100M01: typeof import("../pages/ADM/ADM100M01.vue")['default']
export const ADMADM101M01: typeof import("../pages/ADM/ADM101M01.vue")['default']
export const ADMADM102M01: typeof import("../pages/ADM/ADM102M01.vue")['default']
export const ADMADM103M01: typeof import("../pages/ADM/ADM103M01.vue")['default']
export const ADMADM104M01: typeof import("../pages/ADM/ADM104M01.vue")['default']
export const ADMADM105M01: typeof import("../pages/ADM/ADM105M01.vue")['default']
export const ADMADM106M01: typeof import("../pages/ADM/ADM106M01.vue")['default']
export const ADMADM107M01: typeof import("../pages/ADM/ADM107M01.vue")['default']
export const ADMADM108M01: typeof import("../pages/ADM/ADM108M01.vue")['default']
export const ADMADM109M01: typeof import("../pages/ADM/ADM109M01.vue")['default']
export const ADMADM110M01: typeof import("../pages/ADM/ADM110M01.vue")['default']
export const ADMADM111M01: typeof import("../pages/ADM/ADM111M01.vue")['default']
export const ADMADM112M01: typeof import("../pages/ADM/ADM112M01.vue")['default']
export const ADMADM113M01: typeof import("../pages/ADM/ADM113M01.vue")['default']
export const BATBAT101M01: typeof import("../pages/BAT/BAT101M01.vue")['default']
export const BATBAT102M01: typeof import("../pages/BAT/BAT102M01.vue")['default']
export const BATBAT103M01: typeof import("../pages/BAT/BAT103M01.vue")['default']
export const COMCOM002M00: typeof import("../pages/COM/COM002M00.vue")['default']
export const CONBackCON001M00: typeof import("../pages/CON_back/CON001M00.vue")['default']
export const CONBackCON001M01: typeof import("../pages/CON_back/CON001M01.vue")['default']
export const CONBackCON001S01: typeof import("../pages/CON_back/CON001S01.vue")['default']
export const CONBackCON001S02: typeof import("../pages/CON_back/CON001S02.vue")['default']
export const CONBackCON001S03: typeof import("../pages/CON_back/CON001S03.vue")['default']
export const CONBackCON002M00: typeof import("../pages/CON_back/CON002M00.vue")['default']
export const CONBackCON002S01: typeof import("../pages/CON_back/CON002S01.vue")['default']
export const CONBackCON002S02: typeof import("../pages/CON_back/CON002S02.vue")['default']
export const CONBackCON002S03: typeof import("../pages/CON_back/CON002S03.vue")['default']
export const COVCOV001M01: typeof import("../pages/COV/COV001M01.vue")['default']
export const COVCOV100M00: typeof import("../pages/COV/COV100M00.vue")['default']
export const COVCOV100S01: typeof import("../pages/COV/COV100S01.vue")['default']
export const COVCOV100S02: typeof import("../pages/COV/COV100S02.vue")['default']
export const COVCOV200M00: typeof import("../pages/COV/COV200M00.vue")['default']
export const EXCEXC100M00: typeof import("../pages/EXC/EXC100M00.vue")['default']
export const HCOHCO101M01: typeof import("../pages/HCO/HCO101M01.vue")['default']
export const HOMHOM001M00: typeof import("../pages/HOM/HOM001M00.vue")['default']
export const LOGLOG001M00: typeof import("../pages/LOG/LOG001M00.vue")['default']
export const LOGLOG002M00: typeof import("../pages/LOG/LOG002M00.vue")['default']
export const MAIN: typeof import("../pages/MAIN/index.vue")['default']
export const MEMMEM010S01: typeof import("../pages/MEM/MEM010S01.vue")['default']
export const MEMMEM010S02: typeof import("../pages/MEM/MEM010S02.vue")['default']
export const MEMMEM011S02: typeof import("../pages/MEM/MEM011S02.vue")['default']
export const MEMMEM011S03: typeof import("../pages/MEM/MEM011S03.vue")['default']
export const MEMMEM101M01: typeof import("../pages/MEM/MEM101M01.vue")['default']
export const MEMMEM201M01: typeof import("../pages/MEM/MEM201M01.vue")['default']
export const MEMMEM201M02: typeof import("../pages/MEM/MEM201M02.vue")['default']
export const MEMMEM201M03: typeof import("../pages/MEM/MEM201M03.vue")['default']
export const MENMEN001M01: typeof import("../pages/MEN/MEN001M01.vue")['default']
export const MENMEN004M01: typeof import("../pages/MEN/MEN004M01.vue")['default']
export const MENMEN004S01: typeof import("../pages/MEN/MEN004S01.vue")['default']
export const MENMEN005M01: typeof import("../pages/MEN/MEN005M01.vue")['default']
export const MENMEN005S01: typeof import("../pages/MEN/MEN005S01.vue")['default']
export const MENMEN006M01: typeof import("../pages/MEN/MEN006M01.vue")['default']
export const MENMEN007M01: typeof import("../pages/MEN/MEN007M01.vue")['default']
export const NOTNOT010M00: typeof import("../pages/NOT/NOT010M00.vue")['default']
export const NOTNOT010S01: typeof import("../pages/NOT/NOT010S01.vue")['default']
export const NOTNOT010S02: typeof import("../pages/NOT/NOT010S02.vue")['default']
export const NOTNOT020M00: typeof import("../pages/NOT/NOT020M00.vue")['default']
export const Idx: typeof import("../pages/idx.vue")['default']
export const PubAdminADMADM0108M01: typeof import("../pages/pub/admin/ADM/ADM0108M01.vue")['default']
export const PubAdminADMADM100M01: typeof import("../pages/pub/admin/ADM/ADM100M01.vue")['default']
export const PubAdminADMADM101M01: typeof import("../pages/pub/admin/ADM/ADM101M01.vue")['default']
export const PubAdminADMADM107M01: typeof import("../pages/pub/admin/ADM/ADM107M01.vue")['default']
export const PubAdminADMADM112M01: typeof import("../pages/pub/admin/ADM/ADM112M01.vue")['default']
export const PubAdminADMADMS0017: typeof import("../pages/pub/admin/ADM/ADMS0017.vue")['default']
export const PubAdminADMADMS0018: typeof import("../pages/pub/admin/ADM/ADMS0018.vue")['default']
export const PubAdminADMADMS0019: typeof import("../pages/pub/admin/ADM/ADMS0019.vue")['default']
export const PubAdminADMADMS0020: typeof import("../pages/pub/admin/ADM/ADMS0020.vue")['default']
export const PubAdminADMADMS0021: typeof import("../pages/pub/admin/ADM/ADMS0021.vue")['default']
export const PubAdminADMADMS0023: typeof import("../pages/pub/admin/ADM/ADMS0023.vue")['default']
export const PubAdminADMADMS0024: typeof import("../pages/pub/admin/ADM/ADMS0024.vue")['default']
export const PubAdminADMADMS0025: typeof import("../pages/pub/admin/ADM/ADMS0025.vue")['default']
export const PubAdminADMADMS0026: typeof import("../pages/pub/admin/ADM/ADMS0026.vue")['default']
export const PubAdminADMADMS0045: typeof import("../pages/pub/admin/ADM/ADMS0045.vue")['default']
export const PubAdminADMADMS0P06: typeof import("../pages/pub/admin/ADM/ADMS0P06.vue")['default']
export const PubAdminBATBAT101M01: typeof import("../pages/pub/admin/BAT/BAT101M01.vue")['default']
export const PubAdminBATBAT101P01: typeof import("../pages/pub/admin/BAT/BAT101P01.vue")['default']
export const PubAdminBATBAT102P01: typeof import("../pages/pub/admin/BAT/BAT102P01.vue")['default']
export const PubAdminHOM001M01: typeof import("../pages/pub/admin/HOM001M01.vue")['default']
export const PubAdminLOG001M00: typeof import("../pages/pub/admin/LOG001M00.vue")['default']
export const PubAdminLOG001P09: typeof import("../pages/pub/admin/LOG001P09.vue")['default']
export const PubAdminLOG002M00: typeof import("../pages/pub/admin/LOG002M00.vue")['default']
export const PubAdminMEMMEM001M00: typeof import("../pages/pub/admin/MEM/MEM001M00.vue")['default']
export const PubAdminMEMMEM201M03: typeof import("../pages/pub/admin/MEM/MEM201M03.vue")['default']
export const PubAdminTemplate: typeof import("../pages/pub/admin/Template.vue")['default']
export const PubPublistAdmin: typeof import("../pages/pub/publist_admin.vue")['default']
export const SampleAdminList: typeof import("../pages/sample/Admin_list.vue")['default']
export const SampleBasicGridViewer: typeof import("../pages/sample/BasicGridViewer.vue")['default']
export const SampleComponentLayout: typeof import("../pages/sample/ComponentLayout.vue")['default']
export const SampleDocViewer: typeof import("../pages/sample/DocViewer.vue")['default']
export const SampleEmptyLayout: typeof import("../pages/sample/EmptyLayout.vue")['default']
export const SampleGridViewer: typeof import("../pages/sample/GridViewer.vue")['default']
export const SampleLoginNoEnterPage: typeof import("../pages/sample/LoginNoEnterPage.vue")['default']
export const SamplePdfMakeViewer: typeof import("../pages/sample/PdfMakeViewer.vue")['default']
export const SamplePdfMakeViewerType2: typeof import("../pages/sample/PdfMakeViewerType2.vue")['default']
export const SamplePdfViewer: typeof import("../pages/sample/PdfViewer.vue")['default']
export const Sample: typeof import("../pages/sample/Sample.vue")['default']
export const SampleTemplate: typeof import("../pages/sample/Template.vue")['default']
export const SampleValidation: typeof import("../pages/sample/Validation.vue")['default']
export const SampleMenuList: typeof import("../pages/sample/menu_list.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBATBAT101P01: typeof import("../components/BAT/BAT101P01.vue")['default']
export const LazyBATBAT102P01: typeof import("../components/BAT/BAT102P01.vue")['default']
export const LazyCOMCOM001C01: typeof import("../components/COM/COM001C01.vue")['default']
export const LazyCOMCOM001C02: typeof import("../components/COM/COM001C02.vue")['default']
export const LazyCOMPOPCOM001C01: typeof import("../components/COM/POP/COM001C01.vue")['default']
export const LazyCOMPOPCOM001C02: typeof import("../components/COM/POP/COM001C02.vue")['default']
export const LazyCOMPOPCOM001P01: typeof import("../components/COM/POP/COM001P01.vue")['default']
export const LazyCOMPOPCOM001P02: typeof import("../components/COM/POP/COM001P02.vue")['default']
export const LazyCOMPOPCOM001P03: typeof import("../components/COM/POP/COM001P03.vue")['default']
export const LazyCOMPOPCOM002P01: typeof import("../components/COM/POP/COM002P01.vue")['default']
export const LazyCOMPOPCOM002P02: typeof import("../components/COM/POP/COM002P02.vue")['default']
export const LazyCOMPOPCOM002P03: typeof import("../components/COM/POP/COM002P03.vue")['default']
export const LazyCOMPOPCOM002P04: typeof import("../components/COM/POP/COM002P04.vue")['default']
export const LazyCONBackPOPUPCON001P01: typeof import("../components/CON_back/POPUP/CON001P01.vue")['default']
export const LazyCONBackPOPUPCON002P01: typeof import("../components/CON_back/POPUP/CON002P01.vue")['default']
export const LazyEXCEXC100P00: typeof import("../components/EXC/EXC100P00.vue")['default']
export const LazyEXCEXC100P01: typeof import("../components/EXC/EXC100P01.vue")['default']
export const LazyLOGLOG001M01C00: typeof import("../components/LOG/LOG001M01C00.vue")['default']
export const LazyLOGLOG001M01C01: typeof import("../components/LOG/LOG001M01C01.vue")['default']
export const LazyLOGLOG001M01C02: typeof import("../components/LOG/LOG001M01C02.vue")['default']
export const LazyLOGLOG001P01: typeof import("../components/LOG/LOG001P01.vue")['default']
export const LazyMEMMEM001P01: typeof import("../components/MEM/MEM001P01.vue")['default']
export const LazyMEMMEM002P02: typeof import("../components/MEM/MEM002P02.vue")['default']
export const LazyMEMMEM003P01: typeof import("../components/MEM/MEM003P01.vue")['default']
export const LazyMEMMEM010P01: typeof import("../components/MEM/MEM010P01.vue")['default']
export const LazyMEMMEM010P03: typeof import("../components/MEM/MEM010P03.vue")['default']
export const LazyMEMMEM011P01: typeof import("../components/MEM/MEM011P01.vue")['default']
export const LazyNOTNOT001P01: typeof import("../components/NOT/NOT001P01.vue")['default']
export const LazyNOTNOT020C02: typeof import("../components/NOT/NOT020C02.vue")['default']
export const LazyCommonComAgGrid: typeof import("../components/common/ComAgGrid.vue")['default']
export const LazyCommonComAgGridBasic: typeof import("../components/common/ComAgGridBasic.vue")['default']
export const LazyCommonComCheckbox: typeof import("../components/common/ComCheckbox.vue")['default']
export const LazyCommonComDatePicker: typeof import("../components/common/ComDatePicker.vue")['default']
export const LazyCommonComImage: typeof import("../components/common/ComImage.vue")['default']
export const LazyCommonComPagenation: typeof import("../components/common/ComPagenation.vue")['default']
export const LazyCommonComRadioButton: typeof import("../components/common/ComRadioButton.vue")['default']
export const LazyCommonComResize: typeof import("../components/common/ComResize.vue")['default']
export const LazyCommonComSelectBox: typeof import("../components/common/ComSelectBox.vue")['default']
export const LazyCommonComSpinner: typeof import("../components/common/ComSpinner.vue")['default']
export const LazyCommonComSwiper: typeof import("../components/common/ComSwiper.vue")['default']
export const LazyCommonLayerPopup: typeof import("../components/common/LayerPopup.vue")['default']
export const LazyCommonDocViewer: typeof import("../components/common/doc/DocViewer.vue")['default']
export const LazyCommonPdfMakeLayout: typeof import("../components/common/pdf/PdfMakeLayout.vue")['default']
export const LazyCommonPdfLoadDynamicUrlPDF: typeof import("../components/common/pdf/loadDynamicUrlPDF.vue")['default']
export const LazyCommonPdfPagination: typeof import("../components/common/pdf/pagination.vue")['default']
export const LazyCommonPdfRender: typeof import("../components/common/pdf/pdfRender.vue")['default']
export const LazyDocViewer: typeof import("../components/doc/DocViewer.vue")['default']
export const LazyLoginForm: typeof import("../components/login/LoginForm.vue")['default']
export const LazyMain: typeof import("../components/main/Main.vue")['default']
export const LazyPdfMakeLayout: typeof import("../components/pdf/PdfMakeLayout.vue")['default']
export const LazyPdfLoadDynamicUrlPDF: typeof import("../components/pdf/loadDynamicUrlPDF.vue")['default']
export const LazyPdfPagination: typeof import("../components/pdf/pagination.vue")['default']
export const LazyPdfRender: typeof import("../components/pdf/pdfRender.vue")['default']
export const LazyADMADM100M01: typeof import("../pages/ADM/ADM100M01.vue")['default']
export const LazyADMADM101M01: typeof import("../pages/ADM/ADM101M01.vue")['default']
export const LazyADMADM102M01: typeof import("../pages/ADM/ADM102M01.vue")['default']
export const LazyADMADM103M01: typeof import("../pages/ADM/ADM103M01.vue")['default']
export const LazyADMADM104M01: typeof import("../pages/ADM/ADM104M01.vue")['default']
export const LazyADMADM105M01: typeof import("../pages/ADM/ADM105M01.vue")['default']
export const LazyADMADM106M01: typeof import("../pages/ADM/ADM106M01.vue")['default']
export const LazyADMADM107M01: typeof import("../pages/ADM/ADM107M01.vue")['default']
export const LazyADMADM108M01: typeof import("../pages/ADM/ADM108M01.vue")['default']
export const LazyADMADM109M01: typeof import("../pages/ADM/ADM109M01.vue")['default']
export const LazyADMADM110M01: typeof import("../pages/ADM/ADM110M01.vue")['default']
export const LazyADMADM111M01: typeof import("../pages/ADM/ADM111M01.vue")['default']
export const LazyADMADM112M01: typeof import("../pages/ADM/ADM112M01.vue")['default']
export const LazyADMADM113M01: typeof import("../pages/ADM/ADM113M01.vue")['default']
export const LazyBATBAT101M01: typeof import("../pages/BAT/BAT101M01.vue")['default']
export const LazyBATBAT102M01: typeof import("../pages/BAT/BAT102M01.vue")['default']
export const LazyBATBAT103M01: typeof import("../pages/BAT/BAT103M01.vue")['default']
export const LazyCOMCOM002M00: typeof import("../pages/COM/COM002M00.vue")['default']
export const LazyCONBackCON001M00: typeof import("../pages/CON_back/CON001M00.vue")['default']
export const LazyCONBackCON001M01: typeof import("../pages/CON_back/CON001M01.vue")['default']
export const LazyCONBackCON001S01: typeof import("../pages/CON_back/CON001S01.vue")['default']
export const LazyCONBackCON001S02: typeof import("../pages/CON_back/CON001S02.vue")['default']
export const LazyCONBackCON001S03: typeof import("../pages/CON_back/CON001S03.vue")['default']
export const LazyCONBackCON002M00: typeof import("../pages/CON_back/CON002M00.vue")['default']
export const LazyCONBackCON002S01: typeof import("../pages/CON_back/CON002S01.vue")['default']
export const LazyCONBackCON002S02: typeof import("../pages/CON_back/CON002S02.vue")['default']
export const LazyCONBackCON002S03: typeof import("../pages/CON_back/CON002S03.vue")['default']
export const LazyCOVCOV001M01: typeof import("../pages/COV/COV001M01.vue")['default']
export const LazyCOVCOV100M00: typeof import("../pages/COV/COV100M00.vue")['default']
export const LazyCOVCOV100S01: typeof import("../pages/COV/COV100S01.vue")['default']
export const LazyCOVCOV100S02: typeof import("../pages/COV/COV100S02.vue")['default']
export const LazyCOVCOV200M00: typeof import("../pages/COV/COV200M00.vue")['default']
export const LazyEXCEXC100M00: typeof import("../pages/EXC/EXC100M00.vue")['default']
export const LazyHCOHCO101M01: typeof import("../pages/HCO/HCO101M01.vue")['default']
export const LazyHOMHOM001M00: typeof import("../pages/HOM/HOM001M00.vue")['default']
export const LazyLOGLOG001M00: typeof import("../pages/LOG/LOG001M00.vue")['default']
export const LazyLOGLOG002M00: typeof import("../pages/LOG/LOG002M00.vue")['default']
export const LazyMAIN: typeof import("../pages/MAIN/index.vue")['default']
export const LazyMEMMEM010S01: typeof import("../pages/MEM/MEM010S01.vue")['default']
export const LazyMEMMEM010S02: typeof import("../pages/MEM/MEM010S02.vue")['default']
export const LazyMEMMEM011S02: typeof import("../pages/MEM/MEM011S02.vue")['default']
export const LazyMEMMEM011S03: typeof import("../pages/MEM/MEM011S03.vue")['default']
export const LazyMEMMEM101M01: typeof import("../pages/MEM/MEM101M01.vue")['default']
export const LazyMEMMEM201M01: typeof import("../pages/MEM/MEM201M01.vue")['default']
export const LazyMEMMEM201M02: typeof import("../pages/MEM/MEM201M02.vue")['default']
export const LazyMEMMEM201M03: typeof import("../pages/MEM/MEM201M03.vue")['default']
export const LazyMENMEN001M01: typeof import("../pages/MEN/MEN001M01.vue")['default']
export const LazyMENMEN004M01: typeof import("../pages/MEN/MEN004M01.vue")['default']
export const LazyMENMEN004S01: typeof import("../pages/MEN/MEN004S01.vue")['default']
export const LazyMENMEN005M01: typeof import("../pages/MEN/MEN005M01.vue")['default']
export const LazyMENMEN005S01: typeof import("../pages/MEN/MEN005S01.vue")['default']
export const LazyMENMEN006M01: typeof import("../pages/MEN/MEN006M01.vue")['default']
export const LazyMENMEN007M01: typeof import("../pages/MEN/MEN007M01.vue")['default']
export const LazyNOTNOT010M00: typeof import("../pages/NOT/NOT010M00.vue")['default']
export const LazyNOTNOT010S01: typeof import("../pages/NOT/NOT010S01.vue")['default']
export const LazyNOTNOT010S02: typeof import("../pages/NOT/NOT010S02.vue")['default']
export const LazyNOTNOT020M00: typeof import("../pages/NOT/NOT020M00.vue")['default']
export const LazyIdx: typeof import("../pages/idx.vue")['default']
export const LazyPubAdminADMADM0108M01: typeof import("../pages/pub/admin/ADM/ADM0108M01.vue")['default']
export const LazyPubAdminADMADM100M01: typeof import("../pages/pub/admin/ADM/ADM100M01.vue")['default']
export const LazyPubAdminADMADM101M01: typeof import("../pages/pub/admin/ADM/ADM101M01.vue")['default']
export const LazyPubAdminADMADM107M01: typeof import("../pages/pub/admin/ADM/ADM107M01.vue")['default']
export const LazyPubAdminADMADM112M01: typeof import("../pages/pub/admin/ADM/ADM112M01.vue")['default']
export const LazyPubAdminADMADMS0017: typeof import("../pages/pub/admin/ADM/ADMS0017.vue")['default']
export const LazyPubAdminADMADMS0018: typeof import("../pages/pub/admin/ADM/ADMS0018.vue")['default']
export const LazyPubAdminADMADMS0019: typeof import("../pages/pub/admin/ADM/ADMS0019.vue")['default']
export const LazyPubAdminADMADMS0020: typeof import("../pages/pub/admin/ADM/ADMS0020.vue")['default']
export const LazyPubAdminADMADMS0021: typeof import("../pages/pub/admin/ADM/ADMS0021.vue")['default']
export const LazyPubAdminADMADMS0023: typeof import("../pages/pub/admin/ADM/ADMS0023.vue")['default']
export const LazyPubAdminADMADMS0024: typeof import("../pages/pub/admin/ADM/ADMS0024.vue")['default']
export const LazyPubAdminADMADMS0025: typeof import("../pages/pub/admin/ADM/ADMS0025.vue")['default']
export const LazyPubAdminADMADMS0026: typeof import("../pages/pub/admin/ADM/ADMS0026.vue")['default']
export const LazyPubAdminADMADMS0045: typeof import("../pages/pub/admin/ADM/ADMS0045.vue")['default']
export const LazyPubAdminADMADMS0P06: typeof import("../pages/pub/admin/ADM/ADMS0P06.vue")['default']
export const LazyPubAdminBATBAT101M01: typeof import("../pages/pub/admin/BAT/BAT101M01.vue")['default']
export const LazyPubAdminBATBAT101P01: typeof import("../pages/pub/admin/BAT/BAT101P01.vue")['default']
export const LazyPubAdminBATBAT102P01: typeof import("../pages/pub/admin/BAT/BAT102P01.vue")['default']
export const LazyPubAdminHOM001M01: typeof import("../pages/pub/admin/HOM001M01.vue")['default']
export const LazyPubAdminLOG001M00: typeof import("../pages/pub/admin/LOG001M00.vue")['default']
export const LazyPubAdminLOG001P09: typeof import("../pages/pub/admin/LOG001P09.vue")['default']
export const LazyPubAdminLOG002M00: typeof import("../pages/pub/admin/LOG002M00.vue")['default']
export const LazyPubAdminMEMMEM001M00: typeof import("../pages/pub/admin/MEM/MEM001M00.vue")['default']
export const LazyPubAdminMEMMEM201M03: typeof import("../pages/pub/admin/MEM/MEM201M03.vue")['default']
export const LazyPubAdminTemplate: typeof import("../pages/pub/admin/Template.vue")['default']
export const LazyPubPublistAdmin: typeof import("../pages/pub/publist_admin.vue")['default']
export const LazySampleAdminList: typeof import("../pages/sample/Admin_list.vue")['default']
export const LazySampleBasicGridViewer: typeof import("../pages/sample/BasicGridViewer.vue")['default']
export const LazySampleComponentLayout: typeof import("../pages/sample/ComponentLayout.vue")['default']
export const LazySampleDocViewer: typeof import("../pages/sample/DocViewer.vue")['default']
export const LazySampleEmptyLayout: typeof import("../pages/sample/EmptyLayout.vue")['default']
export const LazySampleGridViewer: typeof import("../pages/sample/GridViewer.vue")['default']
export const LazySampleLoginNoEnterPage: typeof import("../pages/sample/LoginNoEnterPage.vue")['default']
export const LazySamplePdfMakeViewer: typeof import("../pages/sample/PdfMakeViewer.vue")['default']
export const LazySamplePdfMakeViewerType2: typeof import("../pages/sample/PdfMakeViewerType2.vue")['default']
export const LazySamplePdfViewer: typeof import("../pages/sample/PdfViewer.vue")['default']
export const LazySample: typeof import("../pages/sample/Sample.vue")['default']
export const LazySampleTemplate: typeof import("../pages/sample/Template.vue")['default']
export const LazySampleValidation: typeof import("../pages/sample/Validation.vue")['default']
export const LazySampleMenuList: typeof import("../pages/sample/menu_list.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
